### ISSUE TITLE
"setupFiles" and "setupFilesAfterEnv" Jest options do not work properly when using jest-node-exports-resolver

### ISSUE THREAD

**Issue by Maikel-Nait** [k-g-a/jest-node-exports-resolver#14]
In my **jest.config.js** I have a section using **setupFiles** and **setupFilesAfterEnv**, as follows:

> setupFiles: [
> path.resolve(__dirname, './tests/setup.js'),
>  'jest-localstorage-mock',
>  'jest-canvas-mock',
>  ],

> setupFilesAfterEnv: [path.resolve(__dirname, './tests/setupAfterEnv.js')],

On those files I have some additional Jest setup configuration.
However, if adding the exports resolver as explained on this GitHub documentation, eg:

`resolver: 'jest-node-exports-resolver'`

When running any Unit Test, I always get the following error:

> Validation Error:
> Module /plugin-manager/tests/setup.js in the setupFiles option was not found.
>         \<rootDir\> is: /plugin-manager

Not sure what's going on, but it seems the resolver is also trying to find "modules" on my test setup files ??

Content of setup.js:

> import { configure } from 'enzyme';
> import Adapter from 'enzyme-adapter-react-16';
> configure({ adapter: new Adapter(), disableLifecycleMethods: true });

Content of setupAfterEnv.js:

> import '@testing-library/jest-dom/extend-expect';
> import "jest-location-mock";

Is this a bug, or am I missing something ?  Using Jest version **27.5.1**

**Comment by k-g-a** [comment]
Do you experience the same issue with v 1.0.5?

Are you sure that `__dirname` equals `<rootDir>`? In other words, did ou try
```
setupFiles: [
'<rootDir>/tests/setup.js',
'jest-localstorage-mock',
'jest-canvas-mock',
],
```

**Comment by Maikel-Nait** [comment]
Thanks for the reply. Didn't try that, becasue without using this resolver, everthing works fine.  In any case, I switched to latest Jest 27 alpha versions, which support exports resolver out-of-the-box, and it works wonderfully, so I finally gave up on jest-node-exports-resolver
