### ISSUE TITLE
Get `Cannot find module` error after upgrade to Jest 29.0.0+

### ISSUE THREAD

**Issue by hunterdes** [k-g-a/jest-node-exports-resolver#19]
```
Cannot find module '@jest/expect' from 'node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js'
```

Was trying to follow some walk around solution(https://github.com/testing-library/jest-dom/issues/457#issuecomment-1206531887), and it fixes the error by removing the `jest-node-exports-resolver`

Still feel like it needs to be fixed properly.

**Comment by ujwal-setlur** [comment]
Same issue here

**Comment by jorenbroekema** [comment]
Same issue here :(
